repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      args:  ["-l", "88"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'
  - repo: local
    hooks:
      - id: poetry_lock_check
        name: Check if poetry lock file is updated
        entry: |
            python -c "
            from poetry.factory import Factory
            l = Factory().create_poetry('.').locker
            if l.is_locked() and l.is_fresh():
              exit(0)
            else:
              print('run `poetry update` to fix')
              exit(1)
            "
        language: python_venv
        additional_dependencies:
          - poetry
        verbose: True
        files: pyproject.toml
