[tool.poetry]
authors = ["Gleb Khaykin <khaykingleb@gmail.com>"]
version = "0.0.0"
name = "deep-learning-for-audio"
description = "Neural networks used for digital signal processing, speech analysis, and speech synthesis."
repository = "https://github.com/khaykingleb/Deep-Learning-for-Audio"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
hydra-core = "^1.2.0"
torch = "^1.12.0"
torchaudio = "^0.12.0"
transformers = "^4.21.0"
datasets = "^2.4.0"
wandb = "^0.12.21"

[tool.poetry.dev-dependencies]
commitizen = "^2.29.2"
pre-commit = "^2.20.0"
detect-secrets = "^1.3.0"
ipykernel = "^6.15.1"
ipywidgets = "^7.7.1"
matplotlib = "^3.5.2"

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
force_sort_within_sections = true
order_by_type = false
line_length = 88

[tool.semantic_release]
version_variable = [
  "pyproject.toml:version",
  "src/__init__.py:__version__"
]
version_pattern = [
  "Makefile:^VERSION := {version}"
]
upload_to_pypi = false
upload_to_release = false
commit_subject = "chore(release): {version}"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
